import React, { useState, useEffect } from 'react';
import { AlertTriangle, Clock, Camera, Activity, Info } from 'lucide-react';

const AIAlerts = () => {
  const [alerts, setAlerts] = useState([]);

  useEffect(() => {
    // Initial mock alerts
    setAlerts([
      { id: 1, type: 'critical', title: 'Severe Congestion Detected', camera: 'Main Highway Cam 01', time: new Date().toLocaleTimeString(), conf: '0.98', desc: 'Traffic flow has halted. Possible accident or heavy bottleneck.' },
      { id: 2, type: 'warning', title: 'Traffic Spike', camera: 'Downtown Intersection', time: new Date(Date.now() - 60000).toLocaleTimeString(), conf: '0.85', desc: 'Vehicle density increased by 40% in the last 5 minutes.' },
      { id: 3, type: 'danger', title: 'Camera Feed Lost', camera: 'North Bridge Stream', time: new Date(Date.now() - 120000).toLocaleTimeString(), conf: '1.00', desc: 'Connection to RTSP stream timed out. Auto-reconnect failed.' }
    ]);

    // Simulate incoming alerts
    const interval = setInterval(() => {
      if (Math.random() > 0.7) {
        const newAlert = {
          id: Date.now(),
          type: Math.random() > 0.5 ? 'warning' : 'critical',
          title: Math.random() > 0.5 ? 'Rapid Speed Drop' : 'High Vehicle Density',
          camera: `Camera ID ${Math.floor(Math.random() * 5) + 1}`,
          time: new Date().toLocaleTimeString(),
          conf: (Math.random() * 0.2 + 0.8).toFixed(2),
          desc: 'Automated AI detection triggered based on congestion logic.'
        };
        setAlerts(prev => [newAlert, ...prev].slice(0, 10)); // Keep top 10
      }
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  const getSeverityStyle = (type) => {
    switch(type) {
      case 'critical': return { bg: 'rgba(239, 68, 68, 0.1)', border: 'var(--ai-danger)', color: 'var(--ai-danger)' };
      case 'danger': return { bg: 'rgba(239, 68, 68, 0.1)', border: 'var(--ai-danger)', color: 'var(--ai-danger)' };
      case 'warning': return { bg: 'rgba(245, 158, 11, 0.1)', border: 'var(--ai-warning)', color: 'var(--ai-warning)' };
      default: return { bg: 'rgba(59, 130, 246, 0.1)', border: 'var(--ai-neon)', color: 'var(--ai-neon)' };
    }
  };

  return (
    <div style={{ padding: '2rem', maxWidth: '1000px', margin: '0 auto' }}>
      <div style={{ marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '1.8rem', color: 'var(--ai-danger)' }}>
            <AlertTriangle size={28} />
            Operational AI Alerts
          </h1>
          <p style={{ color: 'var(--ai-muted)', marginTop: '0.5rem' }}>
            Live incident reports generated by the YOLOv8 surveillance engine.
          </p>
        </div>
        <div style={{ background: 'rgba(239, 68, 68, 0.2)', padding: '0.5rem 1rem', borderRadius: '20px', color: 'var(--ai-danger)', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div className="live-dot" style={{ background: 'var(--ai-danger)', boxShadow: '0 0 8px var(--ai-danger)' }}></div>
          Monitoring Active
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {alerts.length === 0 && <p style={{ color: 'var(--ai-muted)' }}>No recent alerts.</p>}
        {alerts.map(alert => {
          const style = getSeverityStyle(alert.type);
          const isCritical = alert.type === 'critical' || alert.type === 'danger';
          
          return (
            <div key={alert.id} className={isCritical ? "critical-state" : ""} style={{ 
              background: style.bg, 
              border: `1px solid ${style.border}`, 
              borderRadius: '8px', 
              padding: '1.5rem',
              position: 'relative',
              overflow: 'hidden'
            }}>
              {isCritical && <div style={{ position: 'absolute', top: 0, left: 0, width: '4px', height: '100%', background: style.border }}></div>}
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
                <h3 style={{ margin: 0, color: style.color, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <AlertTriangle size={20} /> {alert.title}
                </h3>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.85rem', color: 'var(--ai-muted)' }}>
                  <Clock size={14} /> {alert.time}
                </div>
              </div>

              <p style={{ margin: '0 0 1rem 0', color: 'var(--ai-text)', lineHeight: '1.5' }}>
                {alert.desc}
              </p>

              <div style={{ display: 'flex', gap: '1.5rem', fontSize: '0.85rem', color: 'var(--ai-muted)', borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '1rem' }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                  <Camera size={14} /> Source: {alert.camera}
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                  <Activity size={14} /> AI Confidence: {(alert.conf * 100).toFixed(0)}%
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default AIAlerts;
